INSERT INTO `categorie` (cat_parent_id, nom) VALUES
NULL, 'OEUFS'),
(NULL, 'LEGUMES'),
(NULL, 'FRUITS'),
(NULL, 'PRODUITS LAITIERS'),
(NULL, 'LA BOULANGE'),
(NULL, 'PLANTES AROMATIQUES & TISANES'),
(NULL, 'AVOINE TRANSFORMEE'),
(NULL, 'BOISSONS'),
(NULL, 'VIANDE'),
(NULL, 'PLANTES'),
(NULL, 'TRICOTS & TISSAGES EN MOHAIR'),
(NULL, 'GLACES'),
(NULL, 'EPICERIE'),
(NULL, 'DIVERS'),
(9, 'Boeuf - Veau'),
(9, 'Volaille - Lapin'),
(8, 'Cidre - Apéritif'),
(9, 'Chèvre'),
(9, 'Mouton - Agneau'),
(13, 'Compotes - Confitures - Miel'),
(9, 'Porc'),
(4, 'Yaourts'),
(8, 'Jus de fruits'),
(13, 'Terrines - Pâtés'),
(5, 'Galettes & Crêpes'),
(5, 'Pains'),
(5, 'Brioches'),
(4, 'Lait'),
(4, 'Fromages au lait de vache'),
(4, 'Fromages au lait de chèvre'),
(4, 'Produits laitiers de Bretonne Pie Noir'),
(10, 'Plantes potagères'),
(10, 'Plantes aromatiques et médicinales vivaces'),
(10, 'Fraisiers et rhubarbe'),
(10, 'Plantes aromatiques et fleurs comestibles annuelles'),
(10, 'Ornementales vivaces'),
(10, 'Ornementales annuelles'),
(13, 'Pâtes sèches'
